  
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/minecraft-313614/docker-minecraft-server:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'eu.gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/minecraft-313614/docker-minecraft-server:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'minecraft-server', '--image', 'gcr.io/minecraft-313614/docker-minecraft-server:$COMMIT_SHA', '--region', 'europe-north1', '--platform', 'managed']
images:
  - 'gcr.io/minecraft-313614/docker-minecraft-server:$COMMIT_SHA'
